"""
train_model.py

Production-ready script to train a RandomForestRegressor on
retail_store_inventory.csv and save the trained model and encoders.

Usage:
    python train_model.py --data_path retail_store_inventory.csv

This script performs:
 - Data loading and exploration
 - Missing value handling
 - Label encoding for categorical features
 - Date decomposition into Year/Month/Day
 - Train/test split (80/20)
 - Random Forest training and evaluation (MAE, RMSE, R2)
 - Feature importance display
 - Save model and encoders with joblib

Author: Generated by GitHub Copilot assistant
"""

import os
import argparse
import logging
from typing import Tuple, Dict, List
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
import joblib

# Configure basic logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def load_data(path: str = None, filename: str = 'retail_store_inventory.csv') -> pd.DataFrame:
    """Load CSV into a pandas DataFrame.

    Behavior:
    - If `path` is provided and exists, load it.
    - Otherwise search the current working directory and all subfolders for
      `filename`.
    - If an exact match is found, use it and print the absolute path.
    - If no exact match but other CSV files exist, use the first CSV found and
      print its location (and warn the user).
    - If nothing is found, raise FileNotFoundError with a helpful message that
      lists the searched directories (sampled to avoid huge messages).

    Works on Windows, Linux, and macOS.
    """
    start = Path.cwd()

    # Debug: print current working directory and list files
    print(f"Current working directory: {start.resolve()}")
    print("Files in the current directory:")
    try:
        for p in sorted(start.iterdir()):
            print(f" - {p.name}")
    except Exception as e:
        print(f"  (could not list directory contents: {e})")

    # If a path was provided explicitly, prefer it when valid
    if path:
        provided = Path(path)
        if provided.is_file():
            abs_path = provided.resolve()
            logging.info(f"Loaded data from provided path: {abs_path}")
            print(f"Found dataset at: {abs_path}")
            return pd.read_csv(abs_path)
        else:
            logging.warning(f"Provided data_path does not exist: {path}. Will search project folders instead.")

    # Walk the project tree and search for the exact filename
    searched_dirs = []
    found_path = None
    for dirpath, dirnames, filenames in os.walk(start):
        searched_dirs.append(dirpath)
        if filename in filenames:
            found_path = Path(dirpath) / filename
            break

    # If exact match found, load it
    if found_path is not None and found_path.is_file():
        abs_found = found_path.resolve()
        logging.info(f"Found dataset at: {abs_found}")
        print(f"Found dataset at: {abs_found}")
        return pd.read_csv(abs_found)

    # No exact match - look for any CSV files and use the first one if present
    first_csv = None
    for dirpath, dirnames, filenames in os.walk(start):
        for f in filenames:
            if f.lower().endswith('.csv'):
                first_csv = Path(dirpath) / f
                break
        if first_csv:
            break

    if first_csv is not None and first_csv.is_file():
        abs_first = first_csv.resolve()
        logging.warning(f"No exact match for '{filename}'. Using first CSV found: {abs_first}")
        print(f"No exact match for '{filename}'. Using first CSV found: {abs_first}")
        return pd.read_csv(abs_first)

    # Nothing found - raise helpful error listing sampled searched locations
    sample_dirs = searched_dirs[:50]
    sample_list = "\n".join(sample_dirs)
    raise FileNotFoundError(
        f"Data file not found: {filename}.\nSearched {len(searched_dirs)} directories starting at: {start.resolve()}\n\n"
        f"Sample of searched directories:\n{sample_list}\n\n"
        f"If your dataset is located elsewhere, provide its full path using --data_path."
    )


def explore_data(df: pd.DataFrame) -> None:
    """Print dataset information: shape, nulls, summary stats."""
    print('\n=== DATA INFO ===')
    df.info()
    print('\n=== SHAPE ===')
    print(df.shape)
    print('\n=== NULL VALUES PER COLUMN ===')
    print(df.isnull().sum())
    print('\n=== SUMMARY STATISTICS ===')
    print(df.describe(include='all'))


def handle_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """Fill missing values: numeric -> median, categorical -> 'Unknown'."""
    df = df.copy()
    # Separate numeric and non-numeric columns
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    object_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

    # Fill numeric with median
    for col in numeric_cols:
        median = df[col].median()
        df[col] = df[col].fillna(median)

    # Fill object/categorical with mode or 'Unknown'
    for col in object_cols:
        if df[col].isnull().sum() > 0:
            try:
                mode = df[col].mode(dropna=True)[0]
            except Exception:
                mode = 'Unknown'
            df[col] = df[col].fillna(mode)

    return df


def encode_categoricals(df: pd.DataFrame, exclude: List[str] = None) -> Tuple[pd.DataFrame, Dict[str, LabelEncoder]]:
    """Label-encode all object/categorical columns and return encoders.

    exclude: list of column names to skip encoding (e.g., Date if present)
    """
    df = df.copy()
    if exclude is None:
        exclude = []
    encoders: Dict[str, LabelEncoder] = {}

    cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
    cat_cols = [c for c in cat_cols if c not in exclude]

    for col in cat_cols:
        le = LabelEncoder()
        # Convert to string to avoid issues
        df[col] = df[col].astype(str)
        df[col] = le.fit_transform(df[col])
        encoders[col] = le
        logging.info(f"Label encoded column: {col}")

    return df, encoders


def extract_date_parts(df: pd.DataFrame, date_col: str = 'Date') -> pd.DataFrame:
    """Convert a Date column to Year, Month, Day and drop original Date column if successful."""
    df = df.copy()
    if date_col not in df.columns:
        logging.info(f"No '{date_col}' column found; skipping date extraction.")
        return df

    # Parse dates robustly
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

    # Extract parts; for NaT values they'll be filled later
    df['Year'] = df[date_col].dt.year
    df['Month'] = df[date_col].dt.month
    df['Day'] = df[date_col].dt.day

    # If extraction produced NaNs, fill with median values
    for col in ['Year', 'Month', 'Day']:
        if df[col].isnull().any():
            median = int(df[col].median(skipna=True)) if not df[col].dropna().empty else 0
            df[col] = df[col].fillna(median).astype(int)

    # Drop the original Date column to avoid leakage
    df = df.drop(columns=[date_col])
    logging.info(f"Extracted Year/Month/Day from {date_col}")
    return df


def prepare_features_and_target(df: pd.DataFrame, target_col: str = 'Demand Forecast') -> Tuple[pd.DataFrame, pd.Series]:
    """Separate features and target. Drop any identifier-like columns if present."""
    # target_col should match the DataFrame's column names (assumed normalized by caller)
    if target_col not in df.columns:
        raise KeyError(f"Target column '{target_col}' not found in dataset. Available columns: {df.columns.tolist()}")

    X = df.drop(columns=[target_col])
    y = df[target_col]
    return X, y


def train_and_evaluate(X: pd.DataFrame, y: pd.Series) -> Tuple[RandomForestRegressor, Dict[str, float], np.ndarray, np.ndarray, List[str]]:
    """Split data, train RandomForest, and evaluate.

    Returns trained model, metrics dict, y_test, y_pred, feature names
    """
    # Train/test split 80/20
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize model
    model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Metrics
    mae = metrics.mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
    r2 = metrics.r2_score(y_test, y_pred)

    metrics_dict = {'MAE': mae, 'RMSE': rmse, 'R2': r2}
    logging.info(f"Training completed. MAE={mae:.4f}, RMSE={rmse:.4f}, R2={r2:.4f}")

    feature_names = X.columns.tolist()
    return model, metrics_dict, y_test.values, y_pred, feature_names


def display_feature_importance(model: RandomForestRegressor, feature_names: List[str], top_n: int = 20) -> None:
    """Print feature importances sorted descending."""
    importances = model.feature_importances_
    feat_imp = sorted(zip(feature_names, importances), key=lambda x: x[1], reverse=True)
    print('\n=== FEATURE IMPORTANCE ===')
    for i, (feat, imp) in enumerate(feat_imp[:top_n], start=1):
        print(f"{i:2d}. {feat}: {imp:.6f}")


def save_artifacts(model: RandomForestRegressor, encoders: Dict[str, LabelEncoder], model_path: str, encoders_dir: str) -> None:
    """Save model and encoders using joblib."""
    # Ensure directories exist
    model_dir = os.path.dirname(model_path) or '.'
    os.makedirs(model_dir, exist_ok=True)
    os.makedirs(encoders_dir, exist_ok=True)

    joblib.dump(model, model_path)
    logging.info(f"Saved trained model to {model_path}")

    # Save encoders as individual files
    for col, enc in encoders.items():
        col_path = os.path.join(encoders_dir, f"encoder_{col}.pkl")
        joblib.dump(enc, col_path)
        logging.info(f"Saved encoder for {col} to {col_path}")


def print_sample_predictions(X_test: pd.DataFrame, y_test: np.ndarray, y_pred: np.ndarray, n: int = 10) -> None:
    """Print a small sample comparison of actual vs predicted values."""
    print('\n=== SAMPLE PREDICTIONS (actual vs predicted) ===')
    sample_n = min(n, len(y_test))
    for i in range(sample_n):
        print(f"Idx {i}: Actual={y_test[i]:.4f}  Predicted={y_pred[i]:.4f}")


def main(args):
    # 1) Data Loading
    df = load_data(args.data_path)
    # 2) Normalize column names to a canonical form: lower_case_with_underscores
    df.columns = [str(c).strip().lower().replace(' ', '_') for c in df.columns]

    # Normalize provided arg names as well
    date_col = args.date_col.strip().lower().replace(' ', '_') if args.date_col else 'date'
    target_col = args.target_col.strip().lower().replace(' ', '_') if args.target_col else 'demand_forecast'

    # 3) Data Exploration
    explore_data(df)

    # 4) Data Preprocessing
    df = handle_missing_values(df)
    df = extract_date_parts(df, date_col=date_col)

    # 5) Encode categoricals (exclude newly created Year/Month/Day which are numeric)
    df, encoders = encode_categoricals(df, exclude=None)

    # 6) Prepare features and target
    X, y = prepare_features_and_target(df, target_col=target_col)

    # 7) Restrict to required features only to avoid feature mismatch with Flask app
    required_features = [
        'inventory_level',
        'units_sold',
        'units_ordered',
        'price',
        'discount',
        'competitor_pricing',
    ]

    missing = [f for f in required_features if f not in X.columns]
    if missing:
        raise KeyError(f"Missing required feature columns: {missing}. Available columns: {X.columns.tolist()}")

    # Keep only these columns in the specified order
    X = X[required_features]

    print('\n=== FEATURE LIST USED FOR TRAINING ===')
    print(required_features)

    # 6) Train and evaluate
    model, metrics_dict, y_test, y_pred, feature_names = train_and_evaluate(X, y)

    # Print metrics
    print('\n=== EVALUATION METRICS ===')
    for k, v in metrics_dict.items():
        print(f"{k}: {v:.6f}")

    # 7) Feature importance
    display_feature_importance(model, feature_names)

    # 8) Sample predictions
    print_sample_predictions(X.iloc[:len(y_test)], y_test, y_pred, n=10)

    # 9) Save model and encoders
    save_artifacts(model, encoders, model_path=args.model_path, encoders_dir=args.encoders_dir)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train demand forecast model')
    parser.add_argument('--data_path', type=str, default='retail_store_inventory.csv', help='Path to CSV dataset')
    parser.add_argument('--date_col', type=str, default='Date', help='Name of date column to parse')
    parser.add_argument('--target_col', type=str, default='Demand Forecast', help='Name of the target column')
    parser.add_argument('--model_path', type=str, default='demand_prediction_model.pkl', help='Path to save trained model')
    parser.add_argument('--encoders_dir', type=str, default='encoders', help='Directory to save label encoders')
    args = parser.parse_args()

    main(args)
